"""empty message

Revision ID: 81791dfcbe07
Revises: a4494d90282b
Create Date: 2024-10-01 22:16:53.288486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81791dfcbe07'
down_revision = 'a4494d90282b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joke', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dislikes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joke', schema=None) as batch_op:
        batch_op.drop_column('dislikes')
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
