"""empty message

Revision ID: 5b3b80f37a68
Revises: 4ef5f5bbeeb6
Create Date: 2024-10-01 20:10:27.778713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3b80f37a68'
down_revision = '4ef5f5bbeeb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('persons', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_column('persons')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
