"""empty message

Revision ID: 6022b0289587
Revises: 445a841bb2b6
Create Date: 2024-09-17 22:21:29.260360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6022b0289587'
down_revision = '445a841bb2b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)

    # ### end Alembic commands ###
